TOPLEVEL_LANG = verilog
VERILOG_SOURCES = cache_storage.v 
TOPLEVEL = cache_storage
MODULE = test_cache_storage
SIM = verilator
export VERILATOR_TRACE=1
export COCOTB_LOG_LEVEL=INFO
export COCOTB_RESULTS_FILE=cocotb_results.xml

include $(shell cocotb-config --makefiles)/Makefile.sim